# Generated by Django 2.2.4 on 2021-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='Sobre nós')),
                ('finance', models.TextField(verbose_name='Finance Outsourcing')),
            ],
            options={
                'verbose_name': 'Sobre nós',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Depositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('work', models.CharField(max_length=50, verbose_name='Empresa ou ocupação')),
                ('deposition', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('emoj', models.ImageField(upload_to='services/', verbose_name='Emotion')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoj_1', models.ImageField(blank=True, null=True, upload_to='strip/1/', verbose_name='Primeiro emoticon')),
                ('title_1', models.CharField(max_length=12, verbose_name='Primeiro título')),
                ('text_1', models.TextField(max_length=100, verbose_name='Primeiro texto')),
                ('emoj_2', models.ImageField(blank=True, null=True, upload_to='strip/2/', verbose_name='Segundo emoticon')),
                ('title_2', models.CharField(max_length=12, verbose_name='Segundo título')),
                ('text_2', models.TextField(max_length=100, verbose_name='Segundo texto')),
                ('emoj_3', models.ImageField(blank=True, null=True, upload_to='strip/3/', verbose_name='Terceiro emoticon')),
                ('title_3', models.CharField(max_length=12, verbose_name='Terceiro título')),
                ('text_3', models.TextField(max_length=100, verbose_name='Terceiro texto')),
                ('emoj_4', models.ImageField(blank=True, null=True, upload_to='strip/4/', verbose_name='Quarto emoticon')),
                ('title_4', models.CharField(max_length=12, verbose_name='Quarto título')),
                ('text_4', models.TextField(max_length=100, verbose_name='Quarto texto')),
            ],
            options={
                'verbose_name': 'Faixa de informações',
            },
        ),
    ]
