# Generated by Django 3.1.5 on 2021-01-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('work', models.CharField(max_length=50, verbose_name='Empresa ou ocupação')),
                ('deposition', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['name'],
            },
        ),
    ]
