# Generated by Django 2.2.4 on 2021-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='emoj',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Emotion'),
        ),
    ]
