# Generated by Django 3.1.5 on 2021-01-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='Sobre nós')),
                ('finance', models.TextField(verbose_name='Finance Outsourcing')),
            ],
            options={
                'verbose_name': 'Sobre nós',
            },
        ),
    ]
