# Generated by Django 2.2.4 on 2021-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_strip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strip',
            name='emoj_1',
            field=models.ImageField(blank=True, null=True, upload_to='strip/1/', verbose_name='Primeiro emoticon'),
        ),
        migrations.AlterField(
            model_name='strip',
            name='emoj_2',
            field=models.ImageField(blank=True, null=True, upload_to='strip/2/', verbose_name='Segundo emoticon'),
        ),
        migrations.AlterField(
            model_name='strip',
            name='emoj_3',
            field=models.ImageField(blank=True, null=True, upload_to='strip/3/', verbose_name='Terceiro emoticon'),
        ),
        migrations.AlterField(
            model_name='strip',
            name='emoj_4',
            field=models.ImageField(blank=True, null=True, upload_to='strip/4/', verbose_name='Quarto emoticon'),
        ),
    ]
